version: '2'
services:
    gateway-cassandra-migration:
        container_name: gateway-cassandra-migration
        environment:
            - CASSANDRA_CONTACT_POINT=gateway-cassandra
            - USER=docker-cassandra-migration
            # - DEBUG_LOG=1 # uncomment to show debug logs durinq the migration process
        build:
            context: .
            dockerfile: cassandra/Cassandra-Migration.Dockerfile
        volumes:
            - ../resources/config/cql:/cql:ro
